dashboardPage(
  dashboardHeader(disable=T),
  dashboardSidebar(disable=T),
  
  dashboardBody(
    # set background to white
    setBackgroundColor(color = "#FFFFFF", shinydashboard = FALSE),
    setBackgroundColor(color = "#FFFFFF", shinydashboard = TRUE),
    tags$head(
      tags$link(rel = "shortcut icon", href = "Good-logo.ico")
    ),
    navbarPage(title=div(img(src="Good logo.png", style = "width:8%;height:10%; position:relative;display:right-align;margin-top:-10px;")),
               theme = shinytheme("lumen"),
               windowTitle = "WASL",
               tabPanel("Source Files",
                        column(width = 12,align = "center",
                               h3("WASL"),
                               p("Wasl Program is designed to address both direct and indirect challenges faced by health center beneficiaries under the Ministry of Health through the use of advanced technical tools."),
                               br(),
                               fluidRow(
                                 column(offset = 3, width = 2, align = "center",downloadButton("id1","Download Excel file")),
                                 column(width = 2, align = "center",downloadButton("id2","Download Power BI")), 
                                 column(width = 2, align = "center",downloadButton("id3","Download PDF"))
                               ),
                               br(),
                               hr(),
                               fluidRow(
                                 column(width = 12,
                                        img(src = "application.png", style = "width:70%;height:70%;")
                                        # embed_url("https://www.youtube.com/watch?v=-IBxIXBaei8") %>%
                                        #   use_bs_responsive()
                                 )
                               )
                        )
               ),
               tabPanel("What is WASL?",
                        h1("WASL Program"),
                        p("The WASL program aims to address all the direct and indirect challenges that health center beneficiaries encounter by utilizing the latest technical tools. The program's components:"),
                        p("Aspects that are directly related to the patient:"),
                        tags$li("Beneficiary's waiting screen"),
                        tags$li("Referral report"),
                        tags$li("Patient Experience Program"),
                        tags$li("Evaluation after the beneficiary leaves."),
                        br(),
                        p("Aspects that are not directly related to the patient:"),
                        tags$li("Working Environment - Delay index"),
                        tags$li("Working Environment- Absenteeism index"),
                        tags$li("Staff documentation index"),
                        br(),
                        h2("1. Waiting Screen"),
                        p("The waiting screen displays the approximate waiting time for the beneficiary in two cases."),
                        tags$li("If a beneficiary has an appointment, the approximate entry time will be displayed for them, with no preference given to one beneficiary over another."),
                        tags$li("If a beneficiary doesn't have an appointment: The center registers all visitors without an appointment as soon as they arrive at the lounge, regardless of whether they have an appointment or not. The waiting screen displays their turn after the last individual with an appointment."),
                        br(),
                        p("Alert: for priority card and expected waiting time:"),
                        tags$li("Beneficiaries with a priority card are provided according to the Ministry's known procedures"),
                        tags$li("The expected waiting time is updated every 5 to 10 minutes based on the number of beneficiaries available whose service has not been completed"),
                        br(),
                        h2("2. Referrals"),
                        p("Referrals are intended to follow up with the beneficiary at the health center."),
                        tags$li("The beneficiary can book appointments in health centers without any difficulties if they require follow-up within the center."),
                        tags$li("If the beneficiary needs follow-up outside the center, the doctor may opt to transfer them to the hospital, which is the responsibility of the referral officer. Interactive reports, including referrals, are also available at the center."),
                        br(),
                        h3("2.1. The difficulty of redirecting patients to the hospital through an appointment system"),
                        p("Once the referral is written, it is received by the competent staff member at the center and booked on available dates in an appointment system. Despite this, the referral officer encounters numerous challenges such as:"),
                        tags$li("No appointments"),
                        tags$li("The system's lack of appointments prevents the beneficiary from receiving the service they deserve."),
                        tags$li("Through the WASL program, referrals that haven't been reserved can be identified in detail and then appropriate solutions can be implemented."),
                        br(),
                        h3("2.2. Assisting Reports"),
                        tags$li("Lack of reports to assist referral staff by clarifying challenges"),
                        tags$li("A connection program can aid in understanding all the challenges that the referral officer faces and address the root of the problem that hinders the beneficiary's service."),
                        br(),
                        h3("2.3. Clarity"),
                        tags$li("Decision makers can find out that there are challenges, but the root of the problem may be unclear and therefore persist"),
                        tags$li("Through a connecting program, all challenges can be known through two stages (we are in the first phase currently)."),
                        br(),
                        p("Relevant entities:"),
                        tags$li("Referral Officer"),
                        tags$li("Referral Supervisor, Management of Centers"),
                        tags$li("Hospital Appointment Manager"),
                        tags$li("Centers"),
                        tags$li("Director of Centre Management"),
                        tags$li("Executive Director"),
                        br(),
                        h2("3. Patient Experience Program"),
                        p("The objective of the program:"),
                        p("After follow-up on communications, it was noted that in many communications, the procedures for providing services to beneficiaries and the job descriptions of the staff of the Center are flawed, and there is no performance measurement to standardize these procedures. Hence, the Patient Experience Program, which aims at:"),
                        tags$li("Standardization of procedures"),
                        tags$li("Lack of clear procedures for each type of communication: The program monitors, categorizes, and categorizes communications, allowing for follow-up and resolution of communication challenges."),
                        tags$li("Daily reports"),
                        tags$li("Lack of reports to assist the patient's experience staff to explain the challenges they face: Through the program, employees can understand all the challenges facing them and then treat the root of the problem that impedes the beneficiary's service."),
                        tags$li("Clarity"),
                        tags$li("Decision makers can find out there are challenges, but the root of the problem may be unclear and therefore persist: All the challenges and procedures followed can be learned in detail through the program."),
                        br(),
                        h2("4. Evaluation following the beneficiary's departure"),
                        tags$li("A one-question questionnaire is sent to the beneficiary: The questionnaire aims to inform beneficiaries who have not received the service about their satisfaction and to collect their feedback so that it can be avoided in the future."),
                        br(),
                        p("There are two cases after sending the questionnaire:"),
                        tags$li("First, the beneficiary should be satisfied. A message of thanks to the beneficiary for expressing a positive opinion."),
                        tags$li("In regards to the beneficiary's dissatisfaction, a message of thanks is sent to them and a request is made for them to provide us with their name and mobile number so that we can contact them and receive their feedback.")
               ),
               tabPanel("ما هو برنامج وصل؟",
                        fluidRow(column(width = 12,
                          align = "right",
                          style = "direction:rtl;",
                          h1("برنامج وصل"),
                          p(" المباشرة وغير المباشرة التي تواجه مستفيدي المراكز الصحية من خلال استخدام أحدث الأدوات التقنية.الجوانب التي يحتويها البرنامج: "),
                          p("الجوانب المباشرة التي لها صلة بالمريض بشكل مباشر:"),
                          tags$li("شاشة انتظار المستفيد"),
                          tags$li("تقرير الإحالات"),
                          tags$li("برنامج تجربة المريض"),
                          tags$li("التقييم بعد خروج المستفيد"),
                          br(),
                          p("الجوانب الغير مباشرة التي ليس لها صله بالمريض بشكل مباشر:"),
                          tags$li("بيئة العمل | مؤشر التأخير"),
                          tags$li("بيئة العمل | مؤشر الغياب"),
                          tags$li("مؤشر وثائق الموظفين"),
                          br(),
                          h2("1. شاشة الانتظار"),
                          p("شاشة انتظار المستفيد توضح وقت الانتظار التقريبي للمستفيد في حالتين:"),
                          tags$li("أن يكون للمستفيد موعد: سوف يظهر الوقت التقريبي لكل مستفيد للدخول بناء على الطبيب أو العيادة دون تقديم مستفيد على آخر"),
                          tags$li("أن لا يكون للمستفيد موعد: يتم تسجيل جميع زوار المركز حتى الذين ليس لديهم مواعيد فور وصولهم لصالة الاستقبال بنفس الطريقة التي يتم تسجيل الذين لديهم مواعيد غير أن شاشة الانتظار تظهر ترتيبهم بعد آخر واحد لديه موعد"),
                          br(),
                          p("تنبيه: بخصوص بطاقة الأولوية والوقت المتوقع للانتظار"),
                          tags$li("يتم تقديم المستفيدين الذين لديهم بطاقة أولوية حسب الإجراءات المعروفة لدى الوزارة"),
                          tags$li("كما أن الوقت المتوقع للانتظار يتم تحديثه كل 5 إلى 10 دقائق بناء على عدد المستفيدين المتواجدين الذي لم يتم الانتهاء من خدمتهم"),
                          br(),
                          h2("2. الإحالات"),
                          p("الإحالات : الهدف منها متابعة المستفيد في المركز الصحي"),
                          tags$li(" في حال كان المستفيد يحتاج إلى متابعة داخل المركز: لا توجد تحديات للمستفيد حيال حجز مواعيد في المراكز الصحية"),
                          tags$li(" في حال كان المستفيد يحتاج إلى متابعة خارج المركز: في حال قرر الطبيب تحويل المستفيد إلى المستشفى يكتب له تحويل وتنتقل مهمة تحويل المستفيد إلى موظف الإحالات كما أن المركز لديه العديد من التقارير المباشرة التفاعلية منها الإحالات"),
                          br(),
                          h3("2.1.  التحديات التي تواجه تحويل المريض إلى المستشفى من خلال نظام موعد:"),
                          p(" بعد كتابة الإحالة للمريض تسلم الإحالة للموظف المختص بالمركز ويقوم بالحجز بناء على المواعيد المتاحة له في نظام موعد غير أن موظف الإحالات يواجه العديد من التحديات مثل:"),
                          tags$li("لا توجد مواعيد"),
                          tags$li("عدم وجود مواعيد متاحة في النظام يعيق من خدمة المستفيد"),
                          tags$li("عن طريق برنامج وصل يمكن تحديد الإحالات التي لم يتم حجز موعد لها بالتفصيل ومن ثم طرح الحلول المناسبة لها"),
                          br(),
                          h3("2.2. التقارير المساعدة"),
                          tags$li("عدم وجود تقارير تساعد موظف الإحالات بتوضيح التحديات التي يواجهها"),
                          tags$li("عن طريق برنامج وصل يمكن فهم جميع التحديات التي تواجه موظف الإحالات ومن ثم علاج جذر المشكلة التي تعيق خدمة المستفيد"),
                          br(),
                          h3("2.3. الوضوح"),
                          tags$li(" يمكن لأصحاب القرار معرفة وجود تحديات لكن جذر المشكلة قد يكون غير واضح ومن ثم استمرارها"),
                          tags$li("عن طريق برنامج وصل يمكن معرفة جميع التحديات من خلال مرحلتين (نحن الآن في المرحلة الأولى) ويسر الله الثانية"),
                          br(),
                          p(":الجهات ذات العلاقة"),
                          tags$li("موظف الإحالات"),
                          tags$li("مشرف الإحالات بإدارة المراكز"),
                          tags$li("مدير المواعيد بالمستشفى"),
                          tags$li("مدير المركز"),
                          tags$li("مدير إدارة المراكز"),
                          tags$li("المدير التنفيذي"),
                          br(),
                          h2("3. برنامج تجربة المريض"),
                          p("الهدف من البرنامج:"),
                          p("بعد متابعة البلاغات لوحظ أن الخلل في كثير من البلاغات في الإجراءات المتبعة لخدمة المستفيد والأوصاف الوظيفية للموظفين بالمركز كما أنه لا توجد أداءه لقياس الإجراءات وتوحيدها من هنا جاء برنامج تجربة المريض والذي يهدف إلى:"),
                          tags$li("توحيد الإجراءات"),
                          tags$li("عدم وجود إجراءات واضحة لكل نوع من أنواع البلاغات  عن طريق البرنامج يتم رصد البلاغات وتصنيفها وتصنيف الإجراءات المتبعة لكل بلاغ حتى يتم متابعة التحديات التي تسبب البلاغات وإيقافها "),
                          tags$li("التقارير اليومية"),
                          tags$li("عدم وجود تقارير تساعد موظف تجربة المريض لشرح التحديات التي يواجهها عن طريق البرنامج يمكن فهم جميع التحديات التي تواجه الموظف ومن ثم علاج جذر المشكلة التي تعيق خدمة المستفيد"),
                          tags$li("الوضوح"),
                          tags$li("يمكن لأصحاب القرار معرفة وجود تحديات لكن جذر المشكلة قد يكون غير واضح ومن ثم استمرارها عن طريق البرنامج يمكن معرفة جميع التحديات والإجراءات المتبعة بالتفصيل"),
                          br(),
                          h2("4. التقييم بعد خروج المستفيد"),
                          tags$li("يتم إرسال استبيان مكون من سؤال واحد للمستفيد. الهدف من الاستبيان التواصل مع جميع من لم تنال الخدمة على رضاه من المستفيدين الذين لديهم مواعيد ومعرفة الملاحظات التي لديهم حتى يتم تفاديها مستقبلا"),
                          br(),
                          p("لدينا حالتان بعد إرسال الاستبيان:"),
                          tags$li("الأولى أن يكون المستفيد راضي: رسالة شكر المستفيد على إبداء رايه الإيجابي"),
                          tags$li("الثانية أن يكون المستفيد غير راضي: رسالة شكر للمستفيد وطلب تزويدنا باسمه ورقم جواله حتى يتم التواصل معه ومعرفة الملاحظات التي لديه")
                        ))
               )
    ),
    
    hr(),
    fluidRow(
      column(width = 1,align = "right", offset = 4,
             tags$a(img(src = "GitHub.png",style = "width:30%;height:30%;"),href = "https://github.com/0abdullah0sami0", target="_blank")),
      column(width = 1,align = "center", offset = 0,
             tags$a(img(src = "LinkedIn.png",style = "width:30%;height:30%;"),href = "https://www.linkedin.com/in/abdullahalshalaan/", target="_blank")),
      column(width = 1,align = "left", offset = 0,
             tags$a(img(src = "twittter.jpeg",style = "width:30%;height:30%;"),href = "https://twitter.com/HR02030", target="_blank"))
    )
  )
)